<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Warehouse.Wms.Application\Warehouse.Wms.Application.csproj" />
    <ProjectReference Include="..\Warehouse.Wms.Infrastructure\Warehouse.Wms.Infrastructure.csproj" />
    <ProjectReference Include="..\Warehouse.DeviceGateway\Warehouse.DeviceGateway.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
