using Microsoft.EntityFrameworkCore;
using Warehouse.Wms.Application.Reports;
using Warehouse.Wms.Infrastructure.Persistence;

namespace Warehouse.Wms.Infrastructure.Reports;

public sealed class SqlServerStatisticsService(IDbContextFactory<WarehouseDbContext> factory) : IStatisticsService
{
    public StatisticsSnapshot? LatestSuccessful => GetSummary();
    public Task<StatisticsSnapshot> GenerateAsync(StatisticsPeriod period, DateTimeOffset periodStart, DateTimeOffset periodEnd, string sourceVersion, bool fail = false, CancellationToken cancellationToken = default)
        => GenerateAsync(new StatisticsBatchRequest(period, periodStart, periodEnd, sourceVersion), fail, cancellationToken);
    public async Task<StatisticsSnapshot> GenerateAsync(StatisticsBatchRequest request, bool fail = false, CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(request); if (request.PeriodEnd <= request.PeriodStart) throw new ArgumentException("periodEnd must be after periodStart"); if (string.IsNullOrWhiteSpace(request.SourceVersion)) throw new ArgumentException("sourceVersion is required"); cancellationToken.ThrowIfCancellationRequested(); if (fail) throw new InvalidOperationException("Statistics generation failed");
        var source = request.SourceVersion.Trim(); await using var db = await factory.CreateDbContextAsync(cancellationToken); var existing = await db.StatisticsBatches.Include(x => x.Trends).Include(x => x.TaskStates).SingleOrDefaultAsync(x => x.Period == request.Period.ToString() && x.PeriodStart == request.PeriodStart && x.PeriodEnd == request.PeriodEnd && x.WarehouseCode == request.WarehouseCode, cancellationToken);
        if (existing is not null) { if (!string.Equals(existing.SourceVersion, source, StringComparison.Ordinal)) throw new InvalidOperationException("A statistics batch already exists for this period and source version."); return Map(existing); }
        var entity = new StatisticsBatchEntity { Id = Guid.NewGuid(), BatchId = CreateBatchId(request), Period = request.Period.ToString(), PeriodStart = request.PeriodStart, PeriodEnd = request.PeriodEnd, GeneratedAt = DateTimeOffset.UtcNow, SourceVersion = source, WarehouseCode = request.WarehouseCode?.Trim(), Freshness = "Fresh" };
        var kpi = request.Kpi ?? new StatisticsKpi(0,0,0,0,0,0,100,0,0); entity.InventoryQuantity=kpi.InventoryQuantity; entity.InventoryWeightKg=kpi.InventoryWeightKg; entity.LocationUtilizationPercent=kpi.LocationUtilizationPercent; entity.InboundQuantity=kpi.InboundQuantity; entity.OutboundQuantity=kpi.OutboundQuantity; entity.TransferQuantity=kpi.TransferQuantity; entity.TaskSuccessRatePercent=kpi.TaskSuccessRatePercent; entity.ExceptionCount=kpi.ExceptionCount; entity.StocktakingDifferenceCount=kpi.StocktakingDifferenceCount;
        foreach (var trend in request.Trends ?? Array.Empty<StatisticsTrendPoint>()) entity.Trends.Add(new StatisticsTrendEntity { Id=Guid.NewGuid(), PeriodStart=trend.PeriodStart, InboundQuantity=trend.InboundQuantity, OutboundQuantity=trend.OutboundQuantity, TransferQuantity=trend.TransferQuantity, ExceptionCount=trend.ExceptionCount });
        foreach (var state in request.TaskStates ?? Array.Empty<TaskStateCount>()) entity.TaskStates.Add(new StatisticsTaskStateEntity { Id=Guid.NewGuid(), State=state.State, Count=state.Count });
        db.StatisticsBatches.Add(entity); try { await db.SaveChangesAsync(cancellationToken); } catch (DbUpdateException) { var winner = await db.StatisticsBatches.Include(x=>x.Trends).Include(x=>x.TaskStates).SingleAsync(x => x.BatchId == entity.BatchId, cancellationToken); if (!string.Equals(winner.SourceVersion, source, StringComparison.Ordinal)) throw new InvalidOperationException("A statistics batch already exists for this period and source version."); return Map(winner); } return Map(entity);
    }
    public StatisticsSnapshot GetSummary(StatisticsPeriod? period = null, string? warehouseCode = null)
    { using var db = factory.CreateDbContext(); var q = db.StatisticsBatches.Include(x=>x.Trends).Include(x=>x.TaskStates).AsNoTracking().AsQueryable(); if (period is not null) q=q.Where(x=>x.Period==period.Value.ToString()); if (!string.IsNullOrWhiteSpace(warehouseCode)) q=q.Where(x=>x.WarehouseCode==warehouseCode.Trim()); var row=q.OrderByDescending(x=>x.GeneratedAt).FirstOrDefault(); return row is null ? new StatisticsSnapshot("STAT-EMPTY", period??StatisticsPeriod.Day, DateTimeOffset.UtcNow.Date.AddDays(-1), DateTimeOffset.UtcNow, DateTimeOffset.UtcNow, "sql-empty", "Delayed", new StatisticsKpi(0,0,0,0,0,0,0,0,0), Array.Empty<StatisticsTrendPoint>(), Array.Empty<TaskStateCount>(), warehouseCode) : Map(row); }
    private static StatisticsSnapshot Map(StatisticsBatchEntity x) => new(x.BatchId, Enum.Parse<StatisticsPeriod>(x.Period), x.PeriodStart, x.PeriodEnd, x.GeneratedAt, x.SourceVersion, x.Freshness, new StatisticsKpi(x.InventoryQuantity,x.InventoryWeightKg,x.LocationUtilizationPercent,x.InboundQuantity,x.OutboundQuantity,x.TransferQuantity,x.TaskSuccessRatePercent,x.ExceptionCount,x.StocktakingDifferenceCount), x.Trends.Select(t=>new StatisticsTrendPoint(t.PeriodStart,t.InboundQuantity,t.OutboundQuantity,t.TransferQuantity,t.ExceptionCount)).ToArray(), x.TaskStates.Select(s=>new TaskStateCount(s.State,s.Count)).ToArray(), x.WarehouseCode);
    private static string CreateBatchId(StatisticsBatchRequest r) => $"STAT-{Convert.ToHexString(System.Security.Cryptography.SHA256.HashData(System.Text.Encoding.UTF8.GetBytes($"{r.Period}:{r.PeriodStart.UtcDateTime:O}:{r.PeriodEnd.UtcDateTime:O}:{r.WarehouseCode?.Trim()??"*"}")))[..16]}";
}
